server:
  port: 8080
spring:
  application:
    name: project-api-gateway
  cloud:
    gateway:
      routes:
        - id: project-authuser-service
          uri: lb://project-authuser-service
          predicates:
            - Path=/project-authuser/**
        - id: project-course-service
          uri: lb://project-course-service
          predicates:
            - Path=/project-course/**
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost