server:
  port: 8087
  servlet:
    context-path: '/project-authuser/'
spring:
    application:
      name: project-authuser-service
    datasource:
      url: jdbc:mysql://localhost:3306/auth_v2?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456
    jpa:
        hibernate:
          ddl-auto: update
          dialect: org.hibernate.dialect.MySQL8Dialect
          jdbc:
            lob.non-contextual-creation: true
        properties:
          hibernate:
            show_sql: true
    output:
      ansi:
        enabled: always
    rabbitmq:
      addresses: amqps://kkozvrft:5dCjABZp-T3KWBMOH6eFrsZBfGq_0Lsf@shark.rmq.cloudamqp.com/kkozvrft
logging:
  level:
    com.organization.project.authuser: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: DEBUG

api:
  url:
    course: 'http://project-course-service/project-course'

broker:
  exchange:
    userEvent: ead.userevent

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost
resilience4j:
  circuitbreaker:
    instances:
      circuitbreakerInstance:
        slidingWindowSize: 30 #janela de tempo em segundos
        permittedNumberOfCallsInHalfOpenState: 2 #limite de requisições em estado meio aberto
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 2 #minimo de chamadas para inicio da avaliação
        waitDurationInOpenState: 30s
        failureRateThreshold: 80 #taxa de falha em % dentro ja janela de tempo para abrir o circuito

  retry:
    instances:
      retryInstance:
        maxRetryAttempts: 3
        waitDuration: 5s