server:
  port: 8087
spring:
    datasource:
      url: jdbc:mysql://localhost:3306/auth?useUnicode=true
      username: root
      password: 123456
    jpa:
        hibernate:
          ddl-auto: update
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
          jdbc:
            lob.non-contextual-creation: true
        properties:
          hibernate:
            show_sql: true
