server:
  port: 8087
  servlet:
    context-path: '/project-authuser/'
spring:
    application:
      name: project-authuser-service
    datasource:
      url: jdbc:mysql://localhost:3306/auth_v2?useUnicode=true
      username: root
      password: 123456
    jpa:
        hibernate:
          ddl-auto: update
          dialect: org.hibernate.dialect.MySQL8Dialect
          jdbc:
            lob.non-contextual-creation: true
        properties:
          hibernate:
            show_sql: true
    output:
      ansi:
        enabled: always
    rabbitmq:
      addresses: 
logging:
  level:
    com.organization.project.authuser: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: DEBUG

api:
  url:
    course: 'http://project-course-service/protect-course'

broker:
  exchange:
    userEvent: ead.userevent

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost