server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/course?useUnicode=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
logging:
  level:
    com.organization.project.authuser: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO
api:
  url:
    auth: 'http://localhost:8087'