server:
  port: 8082
spring:
    application:
      name: project-course-service
    datasource:
      url: jdbc:mysql://localhost:3306/course?useUnicode=true
      username: root
      password: 123456
    jpa:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        jdbc:
          lob.non-contextual-creation: true
      properties:
        hibernate:
          show_sql: true
    output:
      ansi:
        enabled: always
logging:
  level:
    com.organization.project.course: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: DEBUG

api:
  url:
    auth: 'http://localhost:8087'

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost