server:
  port: 8082
  servlet:
    context-path: '/project-course/'
spring:
    application:
      name: project-course-service
    datasource:
      url: jdbc:mysql://localhost:3306/course_v2?useUnicode=true
      username: root
      password: 123456
    jpa:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          lob.non-contextual-creation: true
      properties:
        hibernate:
          show_sql: true
    output:
      ansi:
        enabled: always
    rabbitmq:
      addresses: URL da mq vai aki
logging:
  level:
    com.organization.project.course: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: DEBUG

api:
  url:
    auth: 'http://project-authuser-service/project-authuser'
broker:
  exchange:
    userEvent: ead.userevent
  queue:
    userEventQueue:
      name: ead.userevent.ms.course

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost